### ISSUE TITLE
Option for viewing in fixed height with scrollbars

### ISSUE THREAD

**Issue by bendl** [bendl/bugzilla-board#10]
An option, either injected into the page or added to the dropdown menu when clicking the extension icon, should give the kanban board a fixed height and scrollbars.

This would prevent having a long way to scroll down to see the standard bugs list.

**Comment by smhussain110** [comment]
@bendl I have implemented this also. Check the Pull Request

**Comment by bendl** [comment]
PR #11 and #13 solve this issue. Closing.
