### ISSUE TITLE
Remove console logs from release builds

### ISSUE THREAD

**Issue by bendl** [bendl/bugzilla-board#14]

**Comment by ithompson4** [comment]
Hello Ben, I would like to contribute to this project. Can I work on this bug? Thanks.

**Comment by bendl** [comment]
Hi Iryna, of course! 
Please submit a pull request with your changes

**Comment by ithompson4** [comment]
Ok, thanks

**Comment by ithompson4** [comment]
Ben, could you please provide more details about this issue? Verify if I only have to remove the lines with  console.log("Some text" + something); from all files.

**Comment by bendl** [comment]
Yes I believe that's all that needs to be done.
It's only the app/scripts.babel/contentscript.js file that needs the console.logs removed

**Comment by ithompson4** [comment]
Ok, thank you. I will do it.

**Comment by bendl** [comment]
Closed in PR #17.
