### ISSUE TITLE
Option to view by assignee

### ISSUE THREAD

**Issue by bendl** [bendl/bugzilla-board#7]
An option to change the columns from status to assignee would be helpful.

A quick way to do this right now is to:
`filter: { status: board }">` -> `filter: { assignee: board }">`
and
```js
if(board_sections.indexOf(b_assignee)  == -1) {
      board_sections.push(b_assignee);
}
```
to
```js
if(board_sections.indexOf(b_status)  == -1) {
      board_sections.push(b_status);
}
```

Ideas:
* Button in dropdown menu when clicking on extension in the toolbar
* Insert a button into the webpage to change the view

**Comment by smhussain110** [comment]
@bendl Implemented this feature. Check my PR

**Comment by bendl** [comment]
PR #11 and #13 solve this issue. Closing.
