### ISSUE TITLE
Column width calculation will return floating point numbers

### ISSUE THREAD

**Issue by bendl** [bendl/bugzilla-board#8]
The current calculation to work out what width the column should be can return fractional numbers when the number of columns does not go evenly into 12.

Bug:
```
class="col-sm-{{ 12/board_sections.length }} bz-column"
```
For 5 board sections, 12/5 returns 2.4 so the final class string will be: `col-sm-2.4` which doesn't exist in bootstraps grid system. It causes the columns to be full-width.

Rounding this down using an angular number filter would be the easiest way to fix this.

**Comment by smhussain110** [comment]
@bendl solved! Check the PR

**Comment by bendl** [comment]
Thanks @raza15 .

PR #11 and #13 solve this issue. Closing.
